import numpy as np
x = np.random.randint(0,3,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal !")
array_equal = np.allclose(x, y)
print(array_equal)